dist: trusty
sudo: required
services:
  - docker

env:
  global:
  - DOCKER_VERSION=1.13.1-0~ubuntu-trusty
  matrix:
  - TEST_TARGET: cerebro

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine
  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes docker-engine=${DOCKER_VERSION}
  - docker version
  - docker info

script:
  - make $TEST_TARGET

notifications:
  slack:
    secure: BAhfe6yUwWPmrUB7JIUgIiPmP5b7QG9hldYP7+4WflIbCkMQGdLZdvkqDw9s1dlf0DkKIiX80CJjobH+WGIgh3LEMDzAt/vpkjIYQlFXtGQqk9k4I8MMoGaAKDu3dcMNNab5WGQYPlqhEZnsAsH+PU5fY7Cw2RKiMb4lq6rtCXrB6JKyNnhJ1JcANV2HjwFSzResZQH0AOr70Bw0vqDa+iUx+9yQAizw3I4XO7U8WhkWblW1a0W047TXT8W906Iw7AGD3T831Hl16HsSFIApoCzvZSn5EzjxUdD/mbDnifqa2dtSwnayO7iL5TqvAK7hM20m6H5VwpGbmJXVJXtm0VlazJWihY+p0dRK7mxCE5gNhuFvoD1bZz7ckeBny43k3ztGX1FaYZS+fFn9sI2Jg7zjLqohlLlI+oy06rhZ9gEMTcXoCKhMQ0vKQ5pvSzNCUbBcUiB938QCqqyCt8xh+w4RTHDuCJ/MJVn9HoYOKqcggI9fT/118r7Ganf9gLOkE3jCO3o7MUxvco/s7SkTN6mXwqAy7zL+TBiz39zfOgLo1C7PevlnEQCeJRevz+q105jdZrrQSSLO7ux/OK26WVoVWj7uwsRQ5PIf796yzsIXUnzmzDswfPgger9iDZj1IN8pv2ozocYyctFVpu2taR5rsK1pX9pmpd6VSLAuXlo=